import Head from 'next/head'
import Image from 'next/image'
import Pricing from '../components/Pricing'


//components
import Nav from '../components/Nav'
import Hero from '../components/Hero'
import Features from '../components/Features'
export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        <Hero/>
        <Features/>
        <Pricing/>
      </main>

    
    </div>
  )
}
